-- F3 — staging da coleção xy3 a partir do snapshot pokemontcg-snapshot-2026-10-09 (ADR-034).
-- Pré-requisito: F3-01 aplicado. Rodar primeiro como está (DRY_RUN, não grava nada).
-- Para gravar: trocar false por true na última linha e rodar de novo.
-- O texto entre $snap$ é o arquivo sets/xy3.json exato (SHA-256 2bc5f6e21d79a8ee75c2550c1e1b47205111d90d6d91088bdab033f27d3cbbbe).
SELECT internal.stage_pokemontcg_snapshot_set($snap${
  "set_id": "xy3",
  "total_count": 114,
  "cards": [
    {"id": "xy3-1", "number": "1", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-2", "number": "2", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-3", "number": "3", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "xy3-4", "number": "4", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy3-5", "number": "5", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy3-6", "number": "6", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-7", "number": "7", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-8", "number": "8", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-9", "number": "9", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-10", "number": "10", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-11", "number": "11", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-12", "number": "12", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-13", "number": "13", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-14", "number": "14", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "xy3-15", "number": "15", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-16", "number": "16", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-17", "number": "17", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "xy3-18", "number": "18", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-19", "number": "19", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-20", "number": "20", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy3-21", "number": "21", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-22", "number": "22", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-23", "number": "23", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-24", "number": "24", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "xy3-25", "number": "25", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-26", "number": "26", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-27", "number": "27", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-28", "number": "28", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-29", "number": "29", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-30", "number": "30", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-31", "number": "31", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-32", "number": "32", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-33", "number": "33", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-34", "number": "34", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-35", "number": "35", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-36", "number": "36", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-37", "number": "37", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-38", "number": "38", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-39", "number": "39", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-40", "number": "40", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-41", "number": "41", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-42", "number": "42", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-43", "number": "43", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-44", "number": "44", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-45", "number": "45", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-46", "number": "46", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "xy3-47", "number": "47", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-48", "number": "48", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-49", "number": "49", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-50", "number": "50", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-51", "number": "51", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-52", "number": "52", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-53", "number": "53", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-54", "number": "54", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy3-55", "number": "55", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy3-55a", "number": "55a", "rarity": "Rare Ultra", "tcgplayer_price_keys": []},
    {"id": "xy3-56", "number": "56", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-57", "number": "57", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-58", "number": "58", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "xy3-59", "number": "59", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-60", "number": "60", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-61", "number": "61", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-62", "number": "62", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-63", "number": "63", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "xy3-64", "number": "64", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy3-65", "number": "65", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-66", "number": "66", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-67", "number": "67", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-68", "number": "68", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-69", "number": "69", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-70", "number": "70", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-71", "number": "71", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-72", "number": "72", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-73", "number": "73", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-74", "number": "74", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy3-75", "number": "75", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-76", "number": "76", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-77", "number": "77", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "xy3-78", "number": "78", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-79", "number": "79", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-80", "number": "80", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-81", "number": "81", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-82", "number": "82", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-83", "number": "83", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "xy3-84", "number": "84", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-85", "number": "85", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-86", "number": "86", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-87", "number": "87", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-88", "number": "88", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-89", "number": "89", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-90", "number": "90", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-91", "number": "91", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-92", "number": "92", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-93", "number": "93", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-94", "number": "94", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-95", "number": "95", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-96", "number": "96", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-97", "number": "97", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-98", "number": "98", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-99", "number": "99", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-100", "number": "100", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-101", "number": "101", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-102", "number": "102", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-103", "number": "103", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-104", "number": "104", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy3-105", "number": "105", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy3-106", "number": "106", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy3-107", "number": "107", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy3-108", "number": "108", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy3-109", "number": "109", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy3-110", "number": "110", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy3-111", "number": "111", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy3-112", "number": "112", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy3-113", "number": "113", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]}
  ]
}
$snap$, false);
