-- F3 — staging da coleção sm6 a partir do snapshot pokemontcg-snapshot-2026-10-09 (ADR-034).
-- Pré-requisito: F3-01 aplicado. Rodar primeiro como está (DRY_RUN, não grava nada).
-- Para gravar: trocar false por true na última linha e rodar de novo.
-- O texto entre $snap$ é o arquivo sets/sm6.json exato (SHA-256 9dde9f1ae4100a7f110dc4a1b16eb6b121491b3a7696f95d9b04eebc5e732989).
SELECT internal.stage_pokemontcg_snapshot_set($snap${
  "set_id": "sm6",
  "total_count": 150,
  "cards": [
    {"id": "sm6-1", "number": "1", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-2", "number": "2", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-2a", "number": "2a", "rarity": "Rare", "tcgplayer_price_keys": []},
    {"id": "sm6-3", "number": "3", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-4", "number": "4", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-5", "number": "5", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-6", "number": "6", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-7", "number": "7", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-8", "number": "8", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-9", "number": "9", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-10", "number": "10", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-11", "number": "11", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm6-12", "number": "12", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-13", "number": "13", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-14", "number": "14", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-15", "number": "15", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-16", "number": "16", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-17", "number": "17", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm6-18", "number": "18", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-19", "number": "19", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm6-20", "number": "20", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-21", "number": "21", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-22", "number": "22", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-23", "number": "23", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-24", "number": "24", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-25", "number": "25", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-26", "number": "26", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-27", "number": "27", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-28", "number": "28", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm6-29", "number": "29", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-30", "number": "30", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-31", "number": "31", "rarity": "Rare Prism Star", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-32", "number": "32", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-33", "number": "33", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-34", "number": "34", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-35", "number": "35", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-36", "number": "36", "rarity": "Rare", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm6-37", "number": "37", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-38", "number": "38", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-39", "number": "39", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-40", "number": "40", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-41", "number": "41", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-42", "number": "42", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-43", "number": "43", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-44", "number": "44", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-45", "number": "45", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-46", "number": "46", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-47", "number": "47", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-48", "number": "48", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-49", "number": "49", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-50", "number": "50", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-51", "number": "51", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-52", "number": "52", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-53", "number": "53", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-54", "number": "54", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-55", "number": "55", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-56", "number": "56", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-57", "number": "57", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-58", "number": "58", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-59", "number": "59", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm6-60", "number": "60", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-61", "number": "61", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-62", "number": "62", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm6-63", "number": "63", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-64", "number": "64", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-65", "number": "65", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-66", "number": "66", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-67", "number": "67", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-68", "number": "68", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-69", "number": "69", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm6-70", "number": "70", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-71", "number": "71", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-72", "number": "72", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-73", "number": "73", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-74", "number": "74", "rarity": "Rare Prism Star", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-75", "number": "75", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-76", "number": "76", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-77", "number": "77", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-78", "number": "78", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-79", "number": "79", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-80", "number": "80", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm6-81", "number": "81", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm6-82", "number": "82", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-83", "number": "83", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-84", "number": "84", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-85", "number": "85", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-86", "number": "86", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-87", "number": "87", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-88", "number": "88", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-89", "number": "89", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-90", "number": "90", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-91", "number": "91", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-92", "number": "92", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-93", "number": "93", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-94", "number": "94", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm6-95", "number": "95", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-96", "number": "96", "rarity": "Rare Prism Star", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-97", "number": "97", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-98", "number": "98", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-99", "number": "99", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-100", "number": "100", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-101", "number": "101", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-102", "number": "102", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-102a", "number": "102a", "rarity": "Rare", "tcgplayer_price_keys": []},
    {"id": "sm6-103", "number": "103", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-104", "number": "104", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-105", "number": "105", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm6-106", "number": "106", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-107", "number": "107", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-108", "number": "108", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-109", "number": "109", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-110", "number": "110", "rarity": "Rare Prism Star", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-111", "number": "111", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-112", "number": "112", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-112a", "number": "112a", "rarity": "Uncommon", "tcgplayer_price_keys": []},
    {"id": "sm6-113", "number": "113", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-113a", "number": "113a", "rarity": "Uncommon", "tcgplayer_price_keys": []},
    {"id": "sm6-114", "number": "114", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-115", "number": "115", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-116", "number": "116", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-117", "number": "117", "rarity": "Rare Prism Star", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-118", "number": "118", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm6-119", "number": "119", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-120", "number": "120", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-121", "number": "121", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-122", "number": "122", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-123", "number": "123", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-124", "number": "124", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-125", "number": "125", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-126", "number": "126", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-127", "number": "127", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-128", "number": "128", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-129", "number": "129", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-130", "number": "130", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-131", "number": "131", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-132", "number": "132", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-133", "number": "133", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-134", "number": "134", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-135", "number": "135", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-136", "number": "136", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-137", "number": "137", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-138", "number": "138", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-139", "number": "139", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-140", "number": "140", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-141", "number": "141", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-142", "number": "142", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-143", "number": "143", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-144", "number": "144", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-145", "number": "145", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm6-146", "number": "146", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]}
  ]
}
$snap$, false);
