-- F3 — staging da coleção bw9 a partir do snapshot pokemontcg-snapshot-2026-10-09 (ADR-034).
-- Pré-requisito: F3-01 aplicado. Rodar primeiro como está (DRY_RUN, não grava nada).
-- Para gravar: trocar false por true na última linha e rodar de novo.
-- O texto entre $snap$ é o arquivo sets/bw9.json exato (SHA-256 51874e6371cefe3fd23fb5493250821eb222b8140b2fb2ef26b87e212fba2575).
SELECT internal.stage_pokemontcg_snapshot_set($snap${
  "set_id": "bw9",
  "total_count": 122,
  "cards": [
    {"id": "bw9-1", "number": "1", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-2", "number": "2", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-3", "number": "3", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-4", "number": "4", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-5", "number": "5", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-6", "number": "6", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-7", "number": "7", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-8", "number": "8", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw9-9", "number": "9", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-10", "number": "10", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-11", "number": "11", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-12", "number": "12", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-13", "number": "13", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw9-14", "number": "14", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-15", "number": "15", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-16", "number": "16", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw9-17", "number": "17", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw9-18", "number": "18", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-19", "number": "19", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-20", "number": "20", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-21", "number": "21", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-22", "number": "22", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-23", "number": "23", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-24", "number": "24", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-25", "number": "25", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-26", "number": "26", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-27", "number": "27", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-28", "number": "28", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-29", "number": "29", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-30", "number": "30", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-31", "number": "31", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw9-32", "number": "32", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-33", "number": "33", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw9-34", "number": "34", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-35", "number": "35", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-36", "number": "36", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-37", "number": "37", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-38", "number": "38", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw9-39", "number": "39", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw9-40", "number": "40", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-41", "number": "41", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-42", "number": "42", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-43", "number": "43", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-44", "number": "44", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-45", "number": "45", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-46", "number": "46", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-47", "number": "47", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-48", "number": "48", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-49", "number": "49", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-50", "number": "50", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-51", "number": "51", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-52", "number": "52", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw9-53", "number": "53", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw9-54", "number": "54", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-55", "number": "55", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-56", "number": "56", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw9-57", "number": "57", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-58", "number": "58", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-59", "number": "59", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-60", "number": "60", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-61", "number": "61", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-62", "number": "62", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-63", "number": "63", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-64", "number": "64", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw9-65", "number": "65", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-66", "number": "66", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-67", "number": "67", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw9-68", "number": "68", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-69", "number": "69", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-70", "number": "70", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-71", "number": "71", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-72", "number": "72", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-73", "number": "73", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-74", "number": "74", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-75", "number": "75", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-76", "number": "76", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-77", "number": "77", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-78", "number": "78", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw9-79", "number": "79", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-80", "number": "80", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-81", "number": "81", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-82", "number": "82", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-83", "number": "83", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw9-84", "number": "84", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw9-85", "number": "85", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw9-86", "number": "86", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw9-87", "number": "87", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-88", "number": "88", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-89", "number": "89", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-90", "number": "90", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-91", "number": "91", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-92", "number": "92", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-93", "number": "93", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-94", "number": "94", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-95", "number": "95", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-96", "number": "96", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-97", "number": "97", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-98", "number": "98", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw9-99", "number": "99", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-100", "number": "100", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-101", "number": "101", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw9-102", "number": "102", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-103", "number": "103", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-104", "number": "104", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-105", "number": "105", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-106", "number": "106", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw9-107", "number": "107", "rarity": "Rare ACE", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw9-108", "number": "108", "rarity": "Rare ACE", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw9-109", "number": "109", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw9-110", "number": "110", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw9-111", "number": "111", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw9-112", "number": "112", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw9-113", "number": "113", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw9-114", "number": "114", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw9-115", "number": "115", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw9-116", "number": "116", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw9-117", "number": "117", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw9-118", "number": "118", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw9-119", "number": "119", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw9-120", "number": "120", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw9-121", "number": "121", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw9-122", "number": "122", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]}
  ]
}
$snap$, false);
