-- F3 — staging da coleção sm115 a partir do snapshot pokemontcg-snapshot-2026-10-09 (ADR-034).
-- Pré-requisito: F3-01 aplicado. Rodar primeiro como está (DRY_RUN, não grava nada).
-- Para gravar: trocar false por true na última linha e rodar de novo.
-- O texto entre $snap$ é o arquivo sets/sm115.json exato (SHA-256 fa77752f6cd1c3f183e601fde5e7a02d543dbdd12e493bcdf906c78a5b69219c).
SELECT internal.stage_pokemontcg_snapshot_set($snap${
  "set_id": "sm115",
  "total_count": 69,
  "cards": [
    {"id": "sm115-1", "number": "1", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-2", "number": "2", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-3", "number": "3", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-4", "number": "4", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-5", "number": "5", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-6", "number": "6", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm115-7", "number": "7", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-8", "number": "8", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-9", "number": "9", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm115-10", "number": "10", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-11", "number": "11", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-12", "number": "12", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-13", "number": "13", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-14", "number": "14", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm115-15", "number": "15", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-16", "number": "16", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm115-17", "number": "17", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-18", "number": "18", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm115-19", "number": "19", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-20", "number": "20", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm115-21", "number": "21", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-22", "number": "22", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-23", "number": "23", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-24", "number": "24", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm115-25", "number": "25", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-26", "number": "26", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-27", "number": "27", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-28", "number": "28", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-29", "number": "29", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-30", "number": "30", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-31", "number": "31", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm115-32", "number": "32", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-33", "number": "33", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-34", "number": "34", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-35", "number": "35", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-36", "number": "36", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm115-37", "number": "37", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-38", "number": "38", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-39", "number": "39", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-40", "number": "40", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-41", "number": "41", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-42", "number": "42", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm115-43", "number": "43", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-44", "number": "44", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm115-45", "number": "45", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-46", "number": "46", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-47", "number": "47", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-48", "number": "48", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm115-49", "number": "49", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-50", "number": "50", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-51", "number": "51", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-52", "number": "52", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-53", "number": "53", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-54", "number": "54", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-55", "number": "55", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm115-56", "number": "56", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-57", "number": "57", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-58", "number": "58", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm115-59", "number": "59", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-60", "number": "60", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-61", "number": "61", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-62", "number": "62", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-63", "number": "63", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm115-64", "number": "64", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-65", "number": "65", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm115-66", "number": "66", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm115-67", "number": "67", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm115-68", "number": "68", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm115-69", "number": "69", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]}
  ]
}
$snap$, false);
