-- F3 — staging da coleção sma a partir do snapshot pokemontcg-snapshot-2026-10-09 (ADR-034).
-- Pré-requisito: F3-01 aplicado. Rodar primeiro como está (DRY_RUN, não grava nada).
-- Para gravar: trocar false por true na última linha e rodar de novo.
-- O texto entre $snap$ é o arquivo sets/sma.json exato (SHA-256 4cbb02de3a0ea4bc91235076479df2f79e84e7911966116cd9eee0568ce93805).
SELECT internal.stage_pokemontcg_snapshot_set($snap${
  "set_id": "sma",
  "total_count": 94,
  "cards": [
    {"id": "sma-SV1", "number": "SV1", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV2", "number": "SV2", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV3", "number": "SV3", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV4", "number": "SV4", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV5", "number": "SV5", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV6", "number": "SV6", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV7", "number": "SV7", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV8", "number": "SV8", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV9", "number": "SV9", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV10", "number": "SV10", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV11", "number": "SV11", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV12", "number": "SV12", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV13", "number": "SV13", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV14", "number": "SV14", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV15", "number": "SV15", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV16", "number": "SV16", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV17", "number": "SV17", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV18", "number": "SV18", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV19", "number": "SV19", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV20", "number": "SV20", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV21", "number": "SV21", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV22", "number": "SV22", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV23", "number": "SV23", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV24", "number": "SV24", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV25", "number": "SV25", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV26", "number": "SV26", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV27", "number": "SV27", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV28", "number": "SV28", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV29", "number": "SV29", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV30", "number": "SV30", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV31", "number": "SV31", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV32", "number": "SV32", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV33", "number": "SV33", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV34", "number": "SV34", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV35", "number": "SV35", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV36", "number": "SV36", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV37", "number": "SV37", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV38", "number": "SV38", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV39", "number": "SV39", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV40", "number": "SV40", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV41", "number": "SV41", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV42", "number": "SV42", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV43", "number": "SV43", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV44", "number": "SV44", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV45", "number": "SV45", "rarity": "Rare Shiny", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV46", "number": "SV46", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV47", "number": "SV47", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV48", "number": "SV48", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV49", "number": "SV49", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV50", "number": "SV50", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV51", "number": "SV51", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV52", "number": "SV52", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV53", "number": "SV53", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV54", "number": "SV54", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV55", "number": "SV55", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV56", "number": "SV56", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV57", "number": "SV57", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV58", "number": "SV58", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV59", "number": "SV59", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV60", "number": "SV60", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV61", "number": "SV61", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV62", "number": "SV62", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV63", "number": "SV63", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV64", "number": "SV64", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV65", "number": "SV65", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV66", "number": "SV66", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV67", "number": "SV67", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV68", "number": "SV68", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV69", "number": "SV69", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV70", "number": "SV70", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV71", "number": "SV71", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV72", "number": "SV72", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV73", "number": "SV73", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV74", "number": "SV74", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV75", "number": "SV75", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV76", "number": "SV76", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV77", "number": "SV77", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV78", "number": "SV78", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV79", "number": "SV79", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV80", "number": "SV80", "rarity": "Rare Shiny GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV81", "number": "SV81", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV82", "number": "SV82", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV83", "number": "SV83", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV84", "number": "SV84", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV85", "number": "SV85", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV86", "number": "SV86", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV87", "number": "SV87", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV88", "number": "SV88", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV89", "number": "SV89", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV90", "number": "SV90", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV91", "number": "SV91", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV92", "number": "SV92", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV93", "number": "SV93", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sma-SV94", "number": "SV94", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]}
  ]
}
$snap$, false);
