-- F3 — staging da coleção sm7 a partir do snapshot pokemontcg-snapshot-2026-10-09 (ADR-034).
-- Pré-requisito: F3-01 aplicado. Rodar primeiro como está (DRY_RUN, não grava nada).
-- Para gravar: trocar false por true na última linha e rodar de novo.
-- O texto entre $snap$ é o arquivo sets/sm7.json exato (SHA-256 18c3e2f0c6cb2ebd4b29c6f1b9ccdcb0fde557cb64be367ec724ae38de25daf0).
SELECT internal.stage_pokemontcg_snapshot_set($snap${
  "set_id": "sm7",
  "total_count": 187,
  "cards": [
    {"id": "sm7-1", "number": "1", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-2", "number": "2", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-3", "number": "3", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm7-4", "number": "4", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-5", "number": "5", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-6", "number": "6", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm7-7", "number": "7", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-8", "number": "8", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-9", "number": "9", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-10", "number": "10", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-10a", "number": "10a", "rarity": "Rare Holo", "tcgplayer_price_keys": []},
    {"id": "sm7-11", "number": "11", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-12", "number": "12", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-13", "number": "13", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-14", "number": "14", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-15", "number": "15", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-16", "number": "16", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-17", "number": "17", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-18", "number": "18", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-19", "number": "19", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-20", "number": "20", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-21", "number": "21", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-22", "number": "22", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-23", "number": "23", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-24", "number": "24", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-25", "number": "25", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-26", "number": "26", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-27", "number": "27", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-28", "number": "28", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-29", "number": "29", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-30", "number": "30", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-31", "number": "31", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-32", "number": "32", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-33", "number": "33", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-34", "number": "34", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-35", "number": "35", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-36", "number": "36", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-37", "number": "37", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-38", "number": "38", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm7-39", "number": "39", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-40", "number": "40", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-41", "number": "41", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-42", "number": "42", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-43", "number": "43", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-44", "number": "44", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-45", "number": "45", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-46", "number": "46", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm7-47", "number": "47", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-48", "number": "48", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-49", "number": "49", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-50", "number": "50", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-51", "number": "51", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-52", "number": "52", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-53", "number": "53", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-54", "number": "54", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-55", "number": "55", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-56", "number": "56", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-57", "number": "57", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-58", "number": "58", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-59", "number": "59", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-60", "number": "60", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-61", "number": "61", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm7-62", "number": "62", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-63", "number": "63", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-64", "number": "64", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-65", "number": "65", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-66", "number": "66", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-67", "number": "67", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm7-68", "number": "68", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-69", "number": "69", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-70", "number": "70", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm7-71", "number": "71", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-72", "number": "72", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-73", "number": "73", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-74", "number": "74", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-75", "number": "75", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-76", "number": "76", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-77", "number": "77", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-78", "number": "78", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-79", "number": "79", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-80", "number": "80", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-81", "number": "81", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm7-82", "number": "82", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-83", "number": "83", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-84", "number": "84", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-85", "number": "85", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-86", "number": "86", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-87", "number": "87", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm7-88", "number": "88", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-89", "number": "89", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm7-90", "number": "90", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-91", "number": "91", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-92", "number": "92", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-93", "number": "93", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-94", "number": "94", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-95", "number": "95", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm7-96", "number": "96", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-97", "number": "97", "rarity": "Rare Prism Star", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-98", "number": "98", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm7-99", "number": "99", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm7-100", "number": "100", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm7-101", "number": "101", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-102", "number": "102", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-103", "number": "103", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-104", "number": "104", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-105", "number": "105", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-106", "number": "106", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm7-107", "number": "107", "rarity": "Rare Prism Star", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-108", "number": "108", "rarity": "Rare Prism Star", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-109", "number": "109", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-110", "number": "110", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-111", "number": "111", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-112", "number": "112", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-113", "number": "113", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-114", "number": "114", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-115", "number": "115", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm7-116", "number": "116", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-117", "number": "117", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-118", "number": "118", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-119", "number": "119", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-120", "number": "120", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-121", "number": "121", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm7-122", "number": "122", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-123", "number": "123", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-123a", "number": "123a", "rarity": "Uncommon", "tcgplayer_price_keys": []},
    {"id": "sm7-124", "number": "124", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-125", "number": "125", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-126", "number": "126", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-127", "number": "127", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-128", "number": "128", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-129", "number": "129", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-130", "number": "130", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-131", "number": "131", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-132", "number": "132", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-133", "number": "133", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-134", "number": "134", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-135", "number": "135", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-136", "number": "136", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-137", "number": "137", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-138", "number": "138", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-139", "number": "139", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-140", "number": "140", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-141", "number": "141", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-142", "number": "142", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-143", "number": "143", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-144", "number": "144", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-145", "number": "145", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm7-146", "number": "146", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-147", "number": "147", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-148", "number": "148", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-148a", "number": "148a", "rarity": "Uncommon", "tcgplayer_price_keys": []},
    {"id": "sm7-149", "number": "149", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-150", "number": "150", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-151", "number": "151", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm7-152", "number": "152", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-153", "number": "153", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-154", "number": "154", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-155", "number": "155", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-156", "number": "156", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-157", "number": "157", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-158", "number": "158", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-159", "number": "159", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-160", "number": "160", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-161", "number": "161", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-162", "number": "162", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-163", "number": "163", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-164", "number": "164", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-165", "number": "165", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-166", "number": "166", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-167", "number": "167", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-168", "number": "168", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-169", "number": "169", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-170", "number": "170", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-171", "number": "171", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-172", "number": "172", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-173", "number": "173", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-174", "number": "174", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-175", "number": "175", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-176", "number": "176", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-177", "number": "177", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-177a", "number": "177a", "rarity": "Rare Ultra", "tcgplayer_price_keys": []},
    {"id": "sm7-178", "number": "178", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-179", "number": "179", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-180", "number": "180", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-181", "number": "181", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-182", "number": "182", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm7-183", "number": "183", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]}
  ]
}
$snap$, false);
