-- F3 — staging da coleção xy10 a partir do snapshot pokemontcg-snapshot-2026-10-09 (ADR-034).
-- Pré-requisito: F3-01 aplicado. Rodar primeiro como está (DRY_RUN, não grava nada).
-- Para gravar: trocar false por true na última linha e rodar de novo.
-- O texto entre $snap$ é o arquivo sets/xy10.json exato (SHA-256 c187830d032e41dd389191c84146bc19c90e8e72fd151755f77e94601b237fad).
SELECT internal.stage_pokemontcg_snapshot_set($snap${
  "set_id": "xy10",
  "total_count": 129,
  "cards": [
    {"id": "xy10-1", "number": "1", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-2", "number": "2", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-3", "number": "3", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-4", "number": "4", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-5", "number": "5", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-6", "number": "6", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-7", "number": "7", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-8", "number": "8", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-9", "number": "9", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-10", "number": "10", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-11", "number": "11", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-12", "number": "12", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-13", "number": "13", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "xy10-14", "number": "14", "rarity": "Rare BREAK", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy10-15", "number": "15", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-16", "number": "16", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-17", "number": "17", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-18", "number": "18", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-19", "number": "19", "rarity": "Rare BREAK", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy10-20", "number": "20", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy10-21", "number": "21", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "xy10-22", "number": "22", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-23", "number": "23", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-24", "number": "24", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-25", "number": "25", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy10-26", "number": "26", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy10-27", "number": "27", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-28", "number": "28", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-29", "number": "29", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "xy10-30", "number": "30", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-31", "number": "31", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-32", "number": "32", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-33", "number": "33", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-34", "number": "34", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-35", "number": "35", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-36", "number": "36", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-37", "number": "37", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-38", "number": "38", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-39", "number": "39", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-40", "number": "40", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-41", "number": "41", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-42", "number": "42", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-43", "number": "43", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy10-43a", "number": "43a", "rarity": "Rare Ultra", "tcgplayer_price_keys": []},
    {"id": "xy10-44", "number": "44", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-45", "number": "45", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-46", "number": "46", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-47", "number": "47", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-48", "number": "48", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-49", "number": "49", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-50", "number": "50", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-51", "number": "51", "rarity": "Rare BREAK", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy10-52", "number": "52", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-53", "number": "53", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-54", "number": "54", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy10-54a", "number": "54a", "rarity": "Rare Ultra", "tcgplayer_price_keys": []},
    {"id": "xy10-55", "number": "55", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy10-56", "number": "56", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "xy10-57", "number": "57", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-58", "number": "58", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-59", "number": "59", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-60", "number": "60", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-61", "number": "61", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-62", "number": "62", "rarity": "Rare BREAK", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy10-63", "number": "63", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "xy10-64", "number": "64", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy10-65", "number": "65", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-66", "number": "66", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-67", "number": "67", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-68", "number": "68", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-69", "number": "69", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy10-70", "number": "70", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-71", "number": "71", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-72", "number": "72", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy10-73", "number": "73", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy10-74", "number": "74", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-75", "number": "75", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-76", "number": "76", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-77", "number": "77", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-78", "number": "78", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-79", "number": "79", "rarity": "Rare BREAK", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy10-80", "number": "80", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-81", "number": "81", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-82", "number": "82", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-83", "number": "83", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy10-84", "number": "84", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy10-85", "number": "85", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy10-86", "number": "86", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-87", "number": "87", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-88", "number": "88", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-89", "number": "89", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-90", "number": "90", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-91", "number": "91", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-92", "number": "92", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-93", "number": "93", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-94", "number": "94", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-95", "number": "95", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-96", "number": "96", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-97", "number": "97", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-98", "number": "98", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-99", "number": "99", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-100", "number": "100", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-101", "number": "101", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-102", "number": "102", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-103", "number": "103", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-104", "number": "104", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-105", "number": "105", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-105a", "number": "105a", "rarity": "Rare Ultra", "tcgplayer_price_keys": []},
    {"id": "xy10-106", "number": "106", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-107", "number": "107", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-108", "number": "108", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-109", "number": "109", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-110", "number": "110", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-111", "number": "111", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-111a", "number": "111a", "rarity": "Rare Ultra", "tcgplayer_price_keys": []},
    {"id": "xy10-112", "number": "112", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-113", "number": "113", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-114", "number": "114", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-115", "number": "115", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy10-116", "number": "116", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy10-117", "number": "117", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy10-118", "number": "118", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy10-119", "number": "119", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy10-120", "number": "120", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy10-121", "number": "121", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy10-122", "number": "122", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy10-123", "number": "123", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy10-124", "number": "124", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy10-125", "number": "125", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]}
  ]
}
$snap$, false);
