-- F3 — staging da coleção swsh1 a partir do snapshot pokemontcg-snapshot-2026-10-09 (ADR-034).
-- Pré-requisito: F3-01 aplicado. Rodar primeiro como está (DRY_RUN, não grava nada).
-- Para gravar: trocar false por true na última linha e rodar de novo.
-- O texto entre $snap$ é o arquivo sets/swsh1.json exato (SHA-256 ed123a2e2803d84ffd25a0f0f687d363acaaf56b9cb0bb5833b969300facf250).
SELECT internal.stage_pokemontcg_snapshot_set($snap${
  "set_id": "swsh1",
  "total_count": 216,
  "cards": [
    {"id": "swsh1-1", "number": "1", "rarity": "Rare Holo V", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-2", "number": "2", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-3", "number": "3", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-4", "number": "4", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-5", "number": "5", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-6", "number": "6", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-7", "number": "7", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-8", "number": "8", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-9", "number": "9", "rarity": "Rare Holo V", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-10", "number": "10", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-11", "number": "11", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-12", "number": "12", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-13", "number": "13", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-14", "number": "14", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "swsh1-15", "number": "15", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-16", "number": "16", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-17", "number": "17", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-18", "number": "18", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-19", "number": "19", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-20", "number": "20", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-21", "number": "21", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-22", "number": "22", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-23", "number": "23", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-24", "number": "24", "rarity": "Rare Holo V", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-25", "number": "25", "rarity": "Rare Holo V", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-26", "number": "26", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-27", "number": "27", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-28", "number": "28", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-29", "number": "29", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-30", "number": "30", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-31", "number": "31", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-32", "number": "32", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-33", "number": "33", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-34", "number": "34", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "swsh1-35", "number": "35", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "swsh1-36", "number": "36", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-37", "number": "37", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-38", "number": "38", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-39", "number": "39", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-40", "number": "40", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-41", "number": "41", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-42", "number": "42", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-43", "number": "43", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-44", "number": "44", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-45", "number": "45", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-46", "number": "46", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-47", "number": "47", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-48", "number": "48", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-49", "number": "49", "rarity": "Rare Holo V", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-50", "number": "50", "rarity": "Rare Holo VMAX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-51", "number": "51", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-52", "number": "52", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-53", "number": "53", "rarity": "Rare Holo V", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-54", "number": "54", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-55", "number": "55", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-56", "number": "56", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-57", "number": "57", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-58", "number": "58", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "swsh1-59", "number": "59", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-60", "number": "60", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-61", "number": "61", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-62", "number": "62", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-63", "number": "63", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-64", "number": "64", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "swsh1-65", "number": "65", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-66", "number": "66", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-67", "number": "67", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-68", "number": "68", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-69", "number": "69", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-70", "number": "70", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-71", "number": "71", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-72", "number": "72", "rarity": "Rare Holo V", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-73", "number": "73", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-74", "number": "74", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-75", "number": "75", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "swsh1-76", "number": "76", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "swsh1-77", "number": "77", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-78", "number": "78", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-79", "number": "79", "rarity": "Rare Holo V", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-80", "number": "80", "rarity": "Rare Holo VMAX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-81", "number": "81", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-82", "number": "82", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-83", "number": "83", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-84", "number": "84", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-85", "number": "85", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "swsh1-86", "number": "86", "rarity": "Rare Holo V", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-87", "number": "87", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-88", "number": "88", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-89", "number": "89", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-90", "number": "90", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-91", "number": "91", "rarity": "Rare Holo V", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-92", "number": "92", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-93", "number": "93", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-94", "number": "94", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-95", "number": "95", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-96", "number": "96", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-97", "number": "97", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-98", "number": "98", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-99", "number": "99", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "swsh1-100", "number": "100", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-101", "number": "101", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-102", "number": "102", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-103", "number": "103", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-104", "number": "104", "rarity": "Rare Holo V", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-105", "number": "105", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-106", "number": "106", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-107", "number": "107", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-108", "number": "108", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-109", "number": "109", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-110", "number": "110", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "swsh1-111", "number": "111", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-112", "number": "112", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-113", "number": "113", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-114", "number": "114", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-115", "number": "115", "rarity": "Rare Holo V", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-116", "number": "116", "rarity": "Rare Holo VMAX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-117", "number": "117", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-118", "number": "118", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-119", "number": "119", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "swsh1-120", "number": "120", "rarity": "Rare Holo V", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-121", "number": "121", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-122", "number": "122", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-123", "number": "123", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-124", "number": "124", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "swsh1-125", "number": "125", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-126", "number": "126", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-127", "number": "127", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-128", "number": "128", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "swsh1-129", "number": "129", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-130", "number": "130", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-131", "number": "131", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-132", "number": "132", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-133", "number": "133", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-134", "number": "134", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-135", "number": "135", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-136", "number": "136", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-137", "number": "137", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "swsh1-138", "number": "138", "rarity": "Rare Holo V", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-139", "number": "139", "rarity": "Rare Holo V", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-140", "number": "140", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-141", "number": "141", "rarity": "Rare Holo V", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-142", "number": "142", "rarity": "Rare Holo VMAX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-143", "number": "143", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-144", "number": "144", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-145", "number": "145", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-146", "number": "146", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-147", "number": "147", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-148", "number": "148", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "swsh1-149", "number": "149", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-150", "number": "150", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-151", "number": "151", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-152", "number": "152", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-153", "number": "153", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-154", "number": "154", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-155", "number": "155", "rarity": "Rare Holo V", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-156", "number": "156", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-157", "number": "157", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-158", "number": "158", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-159", "number": "159", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-160", "number": "160", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-161", "number": "161", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-162", "number": "162", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-163", "number": "163", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-164", "number": "164", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-165", "number": "165", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-166", "number": "166", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-167", "number": "167", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-168", "number": "168", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-169", "number": "169", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "swsh1-170", "number": "170", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-171", "number": "171", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-172", "number": "172", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-173", "number": "173", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-174", "number": "174", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-175", "number": "175", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-176", "number": "176", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-177", "number": "177", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-178", "number": "178", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "swsh1-179", "number": "179", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-180", "number": "180", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-181", "number": "181", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-182", "number": "182", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-183", "number": "183", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-184", "number": "184", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-185", "number": "185", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-186", "number": "186", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "swsh1-187", "number": "187", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-188", "number": "188", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-189", "number": "189", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-190", "number": "190", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-191", "number": "191", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-192", "number": "192", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-193", "number": "193", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-194", "number": "194", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-195", "number": "195", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-196", "number": "196", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-197", "number": "197", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-198", "number": "198", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-199", "number": "199", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-200", "number": "200", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-201", "number": "201", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-202", "number": "202", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-203", "number": "203", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-204", "number": "204", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-205", "number": "205", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-206", "number": "206", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-207", "number": "207", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-208", "number": "208", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-209", "number": "209", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-210", "number": "210", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-211", "number": "211", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-212", "number": "212", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-213", "number": "213", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-214", "number": "214", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-215", "number": "215", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "swsh1-216", "number": "216", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]}
  ]
}
$snap$, false);
