-- F3 — staging da coleção sm35 a partir do snapshot pokemontcg-snapshot-2026-10-09 (ADR-034).
-- Pré-requisito: F3-01 aplicado. Rodar primeiro como está (DRY_RUN, não grava nada).
-- Para gravar: trocar false por true na última linha e rodar de novo.
-- O texto entre $snap$ é o arquivo sets/sm35.json exato (SHA-256 46ba4378a680e3a713b2fe3dcae80186ed2d24da3d3672f6ce2d136f06de6412).
SELECT internal.stage_pokemontcg_snapshot_set($snap${
  "set_id": "sm35",
  "total_count": 81,
  "cards": [
    {"id": "sm35-1", "number": "1", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-2", "number": "2", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-3", "number": "3", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-4", "number": "4", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-5", "number": "5", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-6", "number": "6", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-7", "number": "7", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm35-8", "number": "8", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm35-9", "number": "9", "rarity": "Rare Shining", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm35-10", "number": "10", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm35-10a", "number": "10a", "rarity": "Rare Holo GX", "tcgplayer_price_keys": []},
    {"id": "sm35-11", "number": "11", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-12", "number": "12", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-13", "number": "13", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-14", "number": "14", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm35-15", "number": "15", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-16", "number": "16", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-17", "number": "17", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-18", "number": "18", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-19", "number": "19", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-20", "number": "20", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-21", "number": "21", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-22", "number": "22", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-23", "number": "23", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-24", "number": "24", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm35-25", "number": "25", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm35-26", "number": "26", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm35-27", "number": "27", "rarity": "Rare Shining", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm35-28", "number": "28", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-29", "number": "29", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm35-30", "number": "30", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-31", "number": "31", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-32", "number": "32", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm35-33", "number": "33", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-34", "number": "34", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-35", "number": "35", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm35-36", "number": "36", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-37", "number": "37", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-38", "number": "38", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-39", "number": "39", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm35-40", "number": "40", "rarity": "Rare Shining", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm35-41", "number": "41", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm35-42", "number": "42", "rarity": "Rare Shining", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm35-43", "number": "43", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-44", "number": "44", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-45", "number": "45", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm35-46", "number": "46", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-47", "number": "47", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-48", "number": "48", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-49", "number": "49", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-50", "number": "50", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-51", "number": "51", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-52", "number": "52", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-53", "number": "53", "rarity": "Rare Holo GX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm35-54", "number": "54", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm35-55", "number": "55", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "sm35-56", "number": "56", "rarity": "Rare Shining", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm35-57", "number": "57", "rarity": "Rare Shining", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm35-58", "number": "58", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-59", "number": "59", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-60", "number": "60", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-61", "number": "61", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-62", "number": "62", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-63", "number": "63", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-64", "number": "64", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-65", "number": "65", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-66", "number": "66", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-67", "number": "67", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-68", "number": "68", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-68a", "number": "68a", "rarity": "Uncommon", "tcgplayer_price_keys": []},
    {"id": "sm35-69", "number": "69", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-70", "number": "70", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "sm35-71", "number": "71", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm35-72", "number": "72", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm35-73", "number": "73", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm35-74", "number": "74", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm35-75", "number": "75", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm35-76", "number": "76", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm35-77", "number": "77", "rarity": "Rare Rainbow", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "sm35-77a", "number": "77a", "rarity": "Rare Ultra", "tcgplayer_price_keys": []},
    {"id": "sm35-78", "number": "78", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]}
  ]
}
$snap$, false);
