-- F3 — staging da coleção bw11 a partir do snapshot pokemontcg-snapshot-2026-10-09 (ADR-034).
-- Pré-requisito: F3-01 aplicado. Rodar primeiro como está (DRY_RUN, não grava nada).
-- Para gravar: trocar false por true na última linha e rodar de novo.
-- O texto entre $snap$ é o arquivo sets/bw11.json exato (SHA-256 fc165d44579a126191f82648cdd9219a43caf9a5376ca3ebc59f025c1eb37737).
SELECT internal.stage_pokemontcg_snapshot_set($snap${
  "set_id": "bw11",
  "total_count": 140,
  "cards": [
    {"id": "bw11-1", "number": "1", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-2", "number": "2", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-3", "number": "3", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-4", "number": "4", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-5", "number": "5", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-6", "number": "6", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-7", "number": "7", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-8", "number": "8", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-9", "number": "9", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-10", "number": "10", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-11", "number": "11", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-12", "number": "12", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-13", "number": "13", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-14", "number": "14", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-15", "number": "15", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-16", "number": "16", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-17", "number": "17", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-18", "number": "18", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-19", "number": "19", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-20", "number": "20", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-21", "number": "21", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-22", "number": "22", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-23", "number": "23", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-24", "number": "24", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-25", "number": "25", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-26", "number": "26", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-27", "number": "27", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-28", "number": "28", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-29", "number": "29", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-30", "number": "30", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-31", "number": "31", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-32", "number": "32", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-33", "number": "33", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-34", "number": "34", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-35", "number": "35", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-36", "number": "36", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-37", "number": "37", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-38", "number": "38", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-39", "number": "39", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-40", "number": "40", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-41", "number": "41", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-42", "number": "42", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-43", "number": "43", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-44", "number": "44", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-45", "number": "45", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-46", "number": "46", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-47", "number": "47", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-48", "number": "48", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-49", "number": "49", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-50", "number": "50", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-51", "number": "51", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-52", "number": "52", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-53", "number": "53", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-54", "number": "54", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-55", "number": "55", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-56", "number": "56", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-57", "number": "57", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-58", "number": "58", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-59", "number": "59", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-60", "number": "60", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-61", "number": "61", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-62", "number": "62", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-63", "number": "63", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-64", "number": "64", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-65", "number": "65", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-66", "number": "66", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-67", "number": "67", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-68", "number": "68", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-69", "number": "69", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-70", "number": "70", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-71", "number": "71", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-72", "number": "72", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-73", "number": "73", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-74", "number": "74", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-75", "number": "75", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-76", "number": "76", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-77", "number": "77", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-78", "number": "78", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-79", "number": "79", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-80", "number": "80", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-81", "number": "81", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-82", "number": "82", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-83", "number": "83", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-84", "number": "84", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-85", "number": "85", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-86", "number": "86", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-87", "number": "87", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-88", "number": "88", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-89", "number": "89", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-90", "number": "90", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-91", "number": "91", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-92", "number": "92", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-93", "number": "93", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-94", "number": "94", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-95", "number": "95", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-96", "number": "96", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-97", "number": "97", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-98", "number": "98", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-99", "number": "99", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-100", "number": "100", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-101", "number": "101", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-102", "number": "102", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-103", "number": "103", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-104", "number": "104", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-105", "number": "105", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-106", "number": "106", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-107", "number": "107", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-108", "number": "108", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "bw11-109", "number": "109", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-110", "number": "110", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-111", "number": "111", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-112", "number": "112", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-113", "number": "113", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "bw11-114", "number": "114", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-115", "number": "115", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-RC1", "number": "RC1", "rarity": "Common", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-RC2", "number": "RC2", "rarity": "Common", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-RC3", "number": "RC3", "rarity": "Uncommon", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-RC4", "number": "RC4", "rarity": "Uncommon", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-RC5", "number": "RC5", "rarity": "Common", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-RC6", "number": "RC6", "rarity": "Uncommon", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-RC7", "number": "RC7", "rarity": "Uncommon", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-RC8", "number": "RC8", "rarity": "Common", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-RC9", "number": "RC9", "rarity": "Common", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-RC10", "number": "RC10", "rarity": "Uncommon", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-RC11", "number": "RC11", "rarity": "Rare", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-RC12", "number": "RC12", "rarity": "Uncommon", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-RC13", "number": "RC13", "rarity": "Uncommon", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-RC14", "number": "RC14", "rarity": "Uncommon", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-RC15", "number": "RC15", "rarity": "Common", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-RC16", "number": "RC16", "rarity": "Common", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-RC17", "number": "RC17", "rarity": "Common", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-RC18", "number": "RC18", "rarity": "Common", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-RC19", "number": "RC19", "rarity": "Uncommon", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-RC20", "number": "RC20", "rarity": "Common", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-RC21", "number": "RC21", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-RC22", "number": "RC22", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-RC23", "number": "RC23", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-RC24", "number": "RC24", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "bw11-RC25", "number": "RC25", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]}
  ]
}
$snap$, false);
