-- F3 — staging da coleção xy11 a partir do snapshot pokemontcg-snapshot-2026-10-09 (ADR-034).
-- Pré-requisito: F3-01 aplicado. Rodar primeiro como está (DRY_RUN, não grava nada).
-- Para gravar: trocar false por true na última linha e rodar de novo.
-- O texto entre $snap$ é o arquivo sets/xy11.json exato (SHA-256 414dc6b4ca53410a079b83f267a95da97f73c0c106d4a56f6d68fed5d923d138).
SELECT internal.stage_pokemontcg_snapshot_set($snap${
  "set_id": "xy11",
  "total_count": 116,
  "cards": [
    {"id": "xy11-1", "number": "1", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-2", "number": "2", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-3", "number": "3", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-4", "number": "4", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-5", "number": "5", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-6", "number": "6", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-7", "number": "7", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-8", "number": "8", "rarity": "Rare BREAK", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy11-9", "number": "9", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-10", "number": "10", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-11", "number": "11", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "xy11-12", "number": "12", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-13", "number": "13", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-14", "number": "14", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-15", "number": "15", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-16", "number": "16", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-17", "number": "17", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-18", "number": "18", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-19", "number": "19", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-20", "number": "20", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "xy11-21", "number": "21", "rarity": "Rare BREAK", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy11-22", "number": "22", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-23", "number": "23", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-24", "number": "24", "rarity": "Rare BREAK", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy11-25", "number": "25", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-26", "number": "26", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy11-27", "number": "27", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-28", "number": "28", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-29", "number": "29", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-30", "number": "30", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-31", "number": "31", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-32", "number": "32", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-33", "number": "33", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-34", "number": "34", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-35", "number": "35", "rarity": "Rare BREAK", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy11-36", "number": "36", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-37", "number": "37", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-38", "number": "38", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-39", "number": "39", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-40", "number": "40", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "xy11-41", "number": "41", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-42", "number": "42", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-43", "number": "43", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-44", "number": "44", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-45", "number": "45", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-46", "number": "46", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-47", "number": "47", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-48", "number": "48", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-49", "number": "49", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-50", "number": "50", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "xy11-51", "number": "51", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-52", "number": "52", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-53", "number": "53", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-54", "number": "54", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-55", "number": "55", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-56", "number": "56", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-57", "number": "57", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-58", "number": "58", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-59", "number": "59", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-60", "number": "60", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-61", "number": "61", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-62", "number": "62", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-63", "number": "63", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-64", "number": "64", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "xy11-65", "number": "65", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "xy11-66", "number": "66", "rarity": "Rare BREAK", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy11-67", "number": "67", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy11-68", "number": "68", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy11-69", "number": "69", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-70", "number": "70", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-71", "number": "71", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-72", "number": "72", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-73", "number": "73", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "xy11-74", "number": "74", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-75", "number": "75", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy11-76", "number": "76", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-77", "number": "77", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-78", "number": "78", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy11-79", "number": "79", "rarity": "Rare Holo EX", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy11-80", "number": "80", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-81", "number": "81", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "xy11-82", "number": "82", "rarity": "Rare BREAK", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy11-83", "number": "83", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-84", "number": "84", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-85", "number": "85", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-86", "number": "86", "rarity": "Rare Holo", "tcgplayer_price_keys": ["holofoil", "reverseHolofoil"]},
    {"id": "xy11-87", "number": "87", "rarity": "Rare BREAK", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy11-88", "number": "88", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-89", "number": "89", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-90", "number": "90", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-91", "number": "91", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-92", "number": "92", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-93", "number": "93", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-94", "number": "94", "rarity": "Common", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-95", "number": "95", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-96", "number": "96", "rarity": "Rare", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-97", "number": "97", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-98", "number": "98", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-99", "number": "99", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-100", "number": "100", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-101", "number": "101", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-102", "number": "102", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-103", "number": "103", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-104", "number": "104", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-105", "number": "105", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-106", "number": "106", "rarity": "Uncommon", "tcgplayer_price_keys": ["normal", "reverseHolofoil"]},
    {"id": "xy11-107", "number": "107", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy11-108", "number": "108", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy11-109", "number": "109", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy11-110", "number": "110", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy11-111", "number": "111", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy11-112", "number": "112", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy11-113", "number": "113", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy11-114", "number": "114", "rarity": "Rare Ultra", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy11-115", "number": "115", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]},
    {"id": "xy11-116", "number": "116", "rarity": "Rare Secret", "tcgplayer_price_keys": ["holofoil"]}
  ]
}
$snap$, false);
